// Shared page wrapper utilities for consistent dark mode layout
const S = {
  page: {
    minHeight: '100vh',
    background: 'var(--bg-main)',
  },
  content: (maxWidth = '1400px') => ({
    padding: '1.75rem 2rem',
    maxWidth,
    margin: '0 auto',
  }),
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1.75rem',
    flexWrap: 'wrap',
    gap: '1rem',
  },
  card: {
    background: 'rgba(255, 255, 255, 0.7)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: '1px solid rgba(0, 0, 0, 0.08)',
    borderRadius: '1rem',
    boxShadow: '0 4px 24px rgba(0,0,0,0.4)',
  },
  panel: {
    background: 'rgba(255, 255, 255, 0.9)',
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '1rem',
    boxShadow: '0 4px 24px rgba(0,0,0,0.4)',
  },
  label: {
    display: 'block',
    fontSize: '0.7rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: 'var(--text-secondary)',
    marginBottom: '0.375rem',
  },
  divider: {
    borderTop: '1px solid rgba(0, 0, 0, 0.06)',
    margin: '0.75rem 0',
  },
  tableHead: {
    background: 'rgba(255, 255, 255, 0.8)',
    color: 'var(--text-secondary)',
    fontSize: '0.7rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    padding: '0.875rem 1.25rem',
    textAlign: 'left',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
    whiteSpace: 'nowrap',
  },
  tableRow: {
    borderBottom: '1px solid rgba(0, 0, 0, 0.04)',
    transition: 'background 0.15s ease',
    cursor: 'default',
  },
  tableCell: {
    padding: '0.875rem 1.25rem',
    fontSize: '0.875rem',
    color: 'var(--text-primary)',
    verticalAlign: 'middle',
  },
  emptyState: {
    textAlign: 'center',
    padding: '5rem 2rem',
    color: 'var(--text-secondary)',
  },
  input: {
    width: '100%',
    padding: '0.7rem 1rem',
    background: 'rgba(255, 255, 255, 0.6)',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    borderRadius: '0.75rem',
    color: 'var(--text-primary)',
    fontSize: '0.875rem',
    fontFamily: "'Inter', sans-serif",
    outline: 'none',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  select: {
    background: 'rgba(255, 255, 255, 0.8)',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    borderRadius: '0.75rem',
    color: 'var(--text-primary)',
    fontSize: '0.875rem',
    padding: '0.7rem 1rem',
    outline: 'none',
    cursor: 'pointer',
  },
  btnAction: (color = '#a5b4fc', bg = 'rgba(79,70,229,0.12)', border = 'rgba(79,70,229,0.3)', hoverBg = 'rgba(79,70,229,0.25)') => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3rem',
    padding: '0.3rem 0.75rem',
    borderRadius: '0.5rem',
    background: bg,
    border: `1px solid ${border}`,
    color,
    fontSize: '0.75rem',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'background 0.15s ease, transform 0.1s ease',
    whiteSpace: 'nowrap',
    _hoverBg: hoverBg,
  }),
  muted: { color: 'var(--text-muted)', fontStyle: 'italic', fontSize: '0.8rem' },
  pill: (color, bg, border) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    padding: '0.2rem 0.625rem',
    borderRadius: '9999px',
    fontSize: '0.7rem',
    fontWeight: 700,
    background: bg,
    color,
    border: `1px solid ${border}`,
    whiteSpace: 'nowrap',
  }),
}

export default S
